const cards = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "409152",
      name: "La Pino'z Pizza",
      uuid: "28086814-fb0e-4412-ac90-77c4bb592030",
      city: "10",
      area: "Nava Wadaj",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "e02kgxw17hyehnurt5bk",
      cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 27,
      minDeliveryTime: 27,
      maxDeliveryTime: 27,
      slaString: "27 MINS",
      lastMileTravel: 5,
      slugs: {
        restaurant: "lapinoz-pizza-naranpura-naranpura",
        city: "ahmedabad",
      },
      cityState: "10",
      address:
        "SHIVALIK SQUARE, SHOP NO 6, BESIDES PANTALOON, NAVA VADJ, AHMEDABAD",
      locality: "Shivalik Square",
      parentId: 4961,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3900,
        message: "",
        title: "Delivery Charge",
        amount: "3900",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6675056~p=1~eid=00000188-61be-7fe3-7c69-2dd2005a0100",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "15% OFF",
        subHeader: "UPTO ₹80",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "409152",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        lastMileTravel: 5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.0",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "690005",
      name: "Shree Mohanthal Bhojanalay",
      uuid: "b814aabf-1018-4ff2-b2be-0030bbf21bc1",
      city: "10",
      area: "Navrangpura",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "f34657e4f398eec0e714971b58f8be69",
      cuisines: ["North Indian", "Chinese", "Gujarati", "Biryani"],
      tags: [],
      costForTwo: 900,
      costForTwoString: "₹9 FOR TWO",
      deliveryTime: 16,
      minDeliveryTime: 16,
      maxDeliveryTime: 16,
      slaString: "16 MINS",
      lastMileTravel: 0.800000011920929,
      slugs: {
        restaurant: "shree-mohanthal-bhojanalay-navrangpura-navrangpura",
        city: "ahmedabad",
      },
      cityState: "10",
      address:
        "SHOP NO. 5, P.K. HOUSE, B/H M.J. LIBRARY,  ASHRAM ROAD, ELLISBRIDGE, AHMEDABAD,-380006",
      locality: "Ashram road",
      parentId: 410281,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2400,
        message: "",
        title: "Delivery Charge",
        amount: "2400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "690005",
        deliveryTime: 16,
        minDeliveryTime: 16,
        maxDeliveryTime: 16,
        lastMileTravel: 0.800000011920929,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.8",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "52630",
      name: "McDonald's",
      uuid: "c0d944d0-9dc4-40b6-bb90-8979dca113c7",
      city: "10",
      area: "Navrangpura",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "ee5f8e06b300efc07c9fe3f4df40dfc4",
      cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 15,
      minDeliveryTime: 15,
      maxDeliveryTime: 15,
      slaString: "15 MINS",
      lastMileTravel: 1.5,
      slugs: {
        restaurant: "mcdonalds-city-gold-multiplex-ashram-road-navrangpura",
        city: "ahmedabad",
      },
      cityState: "10",
      address:
        "City Gold Multiplex, Ground Floor, Ashram Road, Ahmedabad 380009.",
      locality: "City Gold Multiplex, Ashram Road",
      parentId: 630,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2400,
        message: "",
        title: "Delivery Charge",
        amount: "2400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "40% OFF",
        subHeader: "UPTO ₹80",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "52630",
        deliveryTime: 15,
        minDeliveryTime: 15,
        maxDeliveryTime: 15,
        lastMileTravel: 1.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.2",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "698049",
      name: "TEA POST",
      uuid: "c88554e5-08b1-485f-8cd6-f491316c6e11",
      city: "10",
      area: "Navrangpura",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "585fa3bec86beeaa6a4eb1d418eccd58",
      cuisines: ["Beverages", "Snacks", "Fast Food"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      slaString: "26 MINS",
      lastMileTravel: 3.700000047683716,
      slugs: {
        restaurant: "tea-post-navrangpura-navrangpura-5",
        city: "ahmedabad",
      },
      cityState: "10",
      address:
        "GF-05,SHIVALIK PLAZA,OPP.A.M.A  CENTER,PANJARA POLE,NR.ATIRA  POLYTECHNIC,IIM  ROAD,AMBAWADI,AHMEDABAD-380015",
      locality: "Shivalik Plaza",
      parentId: 4509,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2900,
        message: "",
        title: "Delivery Charge",
        amount: "2900",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6859088~p=13~eid=00000188-61be-7fe3-7c69-2dd6005a0d67",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3.7 kms",
      hasSurge: false,
      sla: {
        restaurantId: "698049",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        lastMileTravel: 3.700000047683716,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "--",
      totalRatings: 0,
      new: true,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "81814",
      name: "Burger King",
      uuid: "10083576-d32d-4a0e-8a82-3236ef342a19",
      city: "10",
      area: "Ellisbridge",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
      cuisines: ["Burgers", "American", "Salads", "Beverages", "Chaat"],
      tags: [],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 19,
      minDeliveryTime: 19,
      maxDeliveryTime: 19,
      slaString: "19 MINS",
      lastMileTravel: 1.7000000476837158,
      slugs: {
        restaurant: "burger-king-parimal-garden-naranpura",
        city: "ahmedabad",
      },
      cityState: "10",
      address:
        "SHOP # 5, GR FLR, THIRD EYE 2,PANCHAVATI CIRCLE, OPP PARIMAL GARDEN,AHMADABAD-382424",
      locality: "3rd Eye II,CG Road",
      parentId: 166,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2400,
        message: "",
        title: "Delivery Charge",
        amount: "2400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.7 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "EVERY ITEM",
        subHeader: "@ ₹129",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "81814",
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        lastMileTravel: 1.7000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "359718",
      name: "Super Dawat Tawa Fry Centre",
      uuid: "ccb48313-7656-4618-96bb-2356677f0a98",
      city: "10",
      area: "Navrangpura",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "ye0cuamd3narriqobmrq",
      cuisines: ["North Indian", "Tandoor", "Biryani", "Seafood"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 15,
      minDeliveryTime: 15,
      maxDeliveryTime: 15,
      slaString: "15 MINS",
      lastMileTravel: 1.7000000476837158,
      slugs: {
        restaurant: "super-dawat-tawa-fry-centre-naranpura-naranpura",
        city: "ahmedabad",
      },
      cityState: "10",
      address:
        "2, Ground Floor, Ambika Niwas Complex, Behind Indusind Bank, Ashram Road, Ahmedabad-380009",
      locality: "Naranpura",
      parentId: 197371,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2400,
        message: "",
        title: "Delivery Charge",
        amount: "2400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.7 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "ABOVE ₹600",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "359718",
        deliveryTime: 15,
        minDeliveryTime: 15,
        maxDeliveryTime: 15,
        lastMileTravel: 1.7000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.6",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "252216",
      name: "Iqbal Hotel-Since 1947",
      uuid: "faa0a25c-8864-4aae-914d-068b8b1a1fed",
      city: "10",
      area: "Sarkhej",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "hnpxjlmt791zx0hiko74",
      cuisines: ["North Indian", "Mughlai", "Chinese", "Biryani"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 32,
      minDeliveryTime: 32,
      maxDeliveryTime: 32,
      slaString: "32 MINS",
      lastMileTravel: 8.800000190734863,
      slugs: {
        restaurant: "iqbal-hotel-sarkhej-sarkhej",
        city: "ahmedabad",
      },
      cityState: "10",
      address:
        "Aman plaza Opp lokhandwala party plot Near canal Fatehwadi Ahmedabad",
      locality: "Fatehwadi",
      parentId: 416449,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 5700,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5700,
        message: "",
        title: "Delivery Charge",
        amount: "5700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6858979~p=7~eid=00000188-61be-7fe3-7c69-2dd4005a0754",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "8.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹150 OFF",
        subHeader: "ABOVE ₹499",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "252216",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        lastMileTravel: 8.800000190734863,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.0",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "108879",
      name: "Jay Jalaram Parotha House",
      uuid: "994e73e1-7c7c-4ad9-87e7-ecfecd4e36fa",
      city: "10",
      area: "Ellisbridge",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "xknto9nqbz7zjjsnnchr",
      cuisines: ["Thalis", "Gujarati", "North Indian", "Punjabi"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 13,
      minDeliveryTime: 13,
      maxDeliveryTime: 13,
      slaString: "13 MINS",
      lastMileTravel: 0.30000001192092896,
      slugs: {
        restaurant: "jay-jalaram-parotha-house-ashram-road-navrangpura",
        city: "ahmedabad",
      },
      cityState: "10",
      address:
        "Capital Commercial Centre, Near UCO Bank, Ashram Road, Ahmedabad",
      locality: "Ashram Road",
      parentId: 7628,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2400,
        message: "",
        title: "Delivery Charge",
        amount: "2400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.3 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "108879",
        deliveryTime: 13,
        minDeliveryTime: 13,
        maxDeliveryTime: 13,
        lastMileTravel: 0.30000001192092896,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.9",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "359871",
      name: "Al Baik Fast Food",
      uuid: "f92856c5-6102-4a3b-9296-e418ed9a0e5c",
      city: "10",
      area: "Lal Darwaja",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "frnc9gss5pppow7lnze0",
      cuisines: ["Arabian", "Grill", "Pizzas", "Seafood", "Tandoor"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 22,
      minDeliveryTime: 22,
      maxDeliveryTime: 22,
      slaString: "22 MINS",
      lastMileTravel: 1.5,
      slugs: {
        restaurant: "al-baik-fast-food-laldarwaja-laldarwaja",
        city: "ahmedabad",
      },
      cityState: "10",
      address:
        "2441/ 1, Advance Cinema Road, Near Sarav Restaurant, Near Bijli Ghar, Lal Darwaja, Ahmedabad",
      locality: "Bhadra Road",
      parentId: 28934,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2400,
        message: "",
        title: "Delivery Charge",
        amount: "2400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹100 OFF",
        subHeader: "ABOVE ₹599",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "359871",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        lastMileTravel: 1.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.2",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "121602",
      name: "Collegian Sandwich Center",
      uuid: "01322bcc-0a70-47e9-bbd2-16a00b423021",
      city: "10",
      area: "Ellis Bridge",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "lyrcmxjmcv2kgisuzida",
      cuisines: ["Street Food"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 15,
      minDeliveryTime: 15,
      maxDeliveryTime: 15,
      slaString: "15 MINS",
      lastMileTravel: 0.30000001192092896,
      slugs: {
        restaurant: "collegian-sandwich-center-ellis-bridge-navrangpura",
        city: "ahmedabad",
      },
      cityState: "10",
      address: "Near Gujrat College, Ellis Bridge, Ahmedabad",
      locality: "",
      parentId: 64548,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2400,
        message: "",
        title: "Delivery Charge",
        amount: "2400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.3 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "121602",
        deliveryTime: 15,
        minDeliveryTime: 15,
        maxDeliveryTime: 15,
        lastMileTravel: 0.30000001192092896,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.8",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "480586",
      name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
      uuid: "985ec709-d249-4716-b9d2-171eaea6dfa1",
      city: "10",
      area: "Navrangpura",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "etwzidtydqmhit6hdc5z",
      cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 16,
      minDeliveryTime: 16,
      maxDeliveryTime: 16,
      slaString: "16 MINS",
      lastMileTravel: 3,
      slugs: {
        restaurant:
          "kwality-wall’s-frozen-dessert-&-ice-cream-shop-navrangpura-navrangpura",
        city: "ahmedabad",
      },
      cityState: "10",
      address:
        "BAIS FOOD SERVICES LLP: UNIT NO 5 & 6, GROUND FLOOR, MADHAV APARTMENTS, PLOT NO 201/201, T P SCHEME NO 20, AHMEDABAD, GUJARAT- 380015 (HUL- I10B301P10711)",
      locality: "Madhav Apartments",
      parentId: 582,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2900,
        message: "",
        title: "Delivery Charge",
        amount: "2900",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6794703~p=13~eid=00000188-61e4-3a1f-7b60-a1f200460d15",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "480586",
        deliveryTime: 16,
        minDeliveryTime: 16,
        maxDeliveryTime: 16,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.4",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "47589",
      name: "Pizza Hut",
      uuid: "465c31fc-bf1b-4f00-8901-571d1a54c718",
      city: "10",
      area: "Navrangpura",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
      cuisines: ["Pizzas"],
      tags: [],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 25,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      slaString: "25 MINS",
      lastMileTravel: 1.7999999523162842,
      slugs: {
        restaurant: "pizza-hut-navrangpura-navrangpura",
        city: "ahmedabad",
      },
      cityState: "10",
      address: "Shop No-956, ground Floor, City gold Complex, Ashramroad",
      locality: "City Gold Complex",
      parentId: 721,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2400,
        message: "",
        title: "Delivery Charge",
        amount: "2400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.7 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "47589",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        lastMileTravel: 1.7999999523162842,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.7",
      totalRatings: 5000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "395939",
      name: "KFC",
      uuid: "76398c0f-223a-4760-824e-5f5a7ae53f1c",
      city: "10",
      area: "Paldi & Ambawadi",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "56c9ab92bd79745fd152a30fa2525426",
      cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 17,
      minDeliveryTime: 17,
      maxDeliveryTime: 17,
      slaString: "17 MINS",
      lastMileTravel: 1.7000000476837158,
      slugs: {
        restaurant: "kfc-panchwati-cross-paldi-ambawadi",
        city: "ahmedabad",
      },
      cityState: "10",
      address:
        "KFC- CG Road - GF 7, Ground Floor , 3rd Eye Two, Near Panchwati Cross Road, CG Road, Ahmedabad 380009",
      locality: "Panchwati Cross",
      parentId: 547,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2400,
        message: "",
        title: "Delivery Charge",
        amount: "2400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.7 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "40% OFF",
        subHeader: "UPTO ₹80",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "395939",
        deliveryTime: 17,
        minDeliveryTime: 17,
        maxDeliveryTime: 17,
        lastMileTravel: 1.7000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.0",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "679926",
      name: "Chinese Wok",
      uuid: "5e72362b-e1cf-4f0d-bb27-ea7119fc82c4",
      city: "10",
      area: "Prahlad Nagar",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "d57fcd0f1cb1dc5994c66ad18854d1b3",
      cuisines: ["Chinese", "Asian", "Tibetan", "Desserts"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 25,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      slaString: "25 MINS",
      lastMileTravel: 6.800000190734863,
      slugs: {
        restaurant: "chinese-wok-vejalpur-prahlad-nagar",
        city: "ahmedabad",
      },
      cityState: "10",
      address:
        "Shop no 12 B, ground floor, Rivera 30, Rivera arcade building, Pralhad Nagar, Vejalpur, Ahmedabad - 380051",
      locality: "Vejalpur",
      parentId: 61955,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 4400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 4400,
        message: "",
        title: "Delivery Charge",
        amount: "4400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6680177~p=16~eid=00000188-61e4-3a1f-7b60-a1f30046107c",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "6.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "15% OFF",
        subHeader: "ABOVE ₹800",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "679926",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        lastMileTravel: 6.800000190734863,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.9",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "513580",
      name: "Shree Marutinandan",
      uuid: "d4502a3d-c220-4a7c-bc6a-721b0273f25b",
      city: "10",
      area: "Navrangpura",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "nxprgfxk9nbskhtjseoz",
      cuisines: ["Gujarati", "North Indian", "Rajasthani"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 18,
      minDeliveryTime: 18,
      maxDeliveryTime: 18,
      slaString: "18 MINS",
      lastMileTravel: 1.899999976158142,
      slugs: {
        restaurant: "shree-marutinandan-navrangpura-navrangpura",
        city: "ahmedabad",
      },
      cityState: "10",
      address:
        "GF/06, THIRD EYE-2, OPP. PARIMAL GARDEN, PANCHAVATI PANCH RASTA, ELLISBRIDGE, AHMEDABAD,, Ahmedabad Municipal Corporation, Ahmedabad Municipal Corporation(Gujarat) -380015",
      locality: "Opp. Parimal Garden",
      parentId: 4934,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2400,
        message: "",
        title: "Delivery Charge",
        amount: "2400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "513580",
        deliveryTime: 18,
        minDeliveryTime: 18,
        maxDeliveryTime: 18,
        lastMileTravel: 1.899999976158142,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.0",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "580135",
      name: "Baskin Robbins Happyness Shakes",
      uuid: "38d323f0-2739-4c8a-bf50-054a83839e24",
      city: "10",
      area: "Navrangpura",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "iniamyqat7bthms7mkms",
      cuisines: ["Desserts", "Ice Cream"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 21,
      minDeliveryTime: 21,
      maxDeliveryTime: 21,
      slaString: "21 MINS",
      lastMileTravel: 1.7000000476837158,
      slugs: {
        restaurant: "baskin-robbins-happyness-shakes-navrangpura-navrangpura",
        city: "ahmedabad",
      },
      cityState: "10",
      address:
        "Baskin Robbins, G/34,35,36 Paiki, Shree Krishna Complex, Mithakhali Six Road, Navrangpura, Ahmedabad, Gujarat - 380006",
      locality: "Navrangpura",
      parentId: 322848,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2400,
        message: "",
        title: "Delivery Charge",
        amount: "2400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6788568~p=19~eid=00000188-61e4-3a1f-7b60-a1f40046136c",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.7 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "30% OFF",
        subHeader: "UPTO ₹75",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "580135",
        deliveryTime: 21,
        minDeliveryTime: 21,
        maxDeliveryTime: 21,
        lastMileTravel: 1.7000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
];

const latestCards = {
  card: {
    card: {
      "@type": "type.googleapis.com/swiggy.gandalf.widgets.v2.GridWidget",
      layout: {
        columns: 4,
      },
      id: "restaurant_grid_listing",
      gridElements: {
        infoWithStyle: {
          "@type":
            "type.googleapis.com/swiggy.presentation.food.v2.FavouriteRestaurantInfoWithStyle",
          restaurants: [
            {
              info: {
                id: "38230",
                name: "Shivam Bhojnalay",
                cloudinaryImageId: "dryrg4zspcdmpbzdvtfp",
                locality: "Gurukul",
                areaName: "Ahmedabad",
                costForTwo: "₹200 for two",
                cuisines: [
                  "Thalis",
                  "Punjabi",
                  "Gujarati",
                  "North Indian",
                  "Rajasthani",
                  "Desserts",
                ],
                avgRating: 4,
                veg: true,
                parentId: "183566",
                avgRatingString: "4.0",
                totalRatingsString: "10K+",
                sla: {
                  deliveryTime: 22,
                  lastMileTravel: 3,
                  serviceability: "SERVICEABLE",
                  slaString: "22 mins",
                  lastMileTravelString: "3.0 km",
                  iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                  nextCloseTime: "2023-12-24 23:59:00",
                  opened: true,
                },
                badges: {
                  imageBadges: [
                    {
                      imageId: "v1695133679/badges/Pure_Veg111.png",
                      description: "pureveg",
                    },
                  ],
                },
                isOpen: true,
                type: "F",
                badgesV2: {
                  entityBadges: {
                    imageBased: {
                      badgeObject: [
                        {
                          attributes: {
                            description: "pureveg",
                            imageId: "v1695133679/badges/Pure_Veg111.png",
                          },
                        },
                      ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                  },
                },
                aggregatedDiscountInfoV3: {
                  header: "60% OFF",
                  discountTag: "FLAT DEAL",
                },
                orderabilityCommunication: {
                  title: {},
                  subTitle: {},
                  message: {},
                  customIcon: {},
                },
                differentiatedUi: {
                  displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                  differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                  },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
              },
              analytics: {
                context: "seo-data-58ab30b8-92c0-4ba5-b059-c403c4364cda",
              },
              cta: {
                link: "https://www.swiggy.com/restaurants/shivam-bhojnalay-gurukul-ahmedabad-ahmedabad-38230",
                text: "RESTAURANT_MENU",
                type: "WEBLINK",
              },
              widgetId:
                "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
            },
            {
              info: {
                id: "37941",
                name: "KFC",
                cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
                locality: "Vastrapur Lake",
                areaName: "Vastrapur",
                costForTwo: "₹400 for two",
                cuisines: [
                  "Burgers",
                  "Biryani",
                  "American",
                  "Snacks",
                  "Fast Food",
                ],
                avgRating: 4.2,
                parentId: "547",
                avgRatingString: "4.2",
                totalRatingsString: "5K+",
                sla: {
                  deliveryTime: 23,
                  lastMileTravel: 3,
                  serviceability: "SERVICEABLE",
                  slaString: "23 mins",
                  lastMileTravelString: "3.0 km",
                  iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                  nextCloseTime: "2023-12-25 03:00:00",
                  opened: true,
                },
                badges: {},
                isOpen: true,
                type: "F",
                badgesV2: {
                  entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                  },
                },
                aggregatedDiscountInfoV3: {
                  header: "40% OFF",
                  subHeader: "UPTO ₹80",
                },
                orderabilityCommunication: {
                  title: {},
                  subTitle: {},
                  message: {},
                  customIcon: {},
                },
                differentiatedUi: {
                  displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                  differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                  },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
              },
              analytics: {
                context: "seo-data-58ab30b8-92c0-4ba5-b059-c403c4364cda",
              },
              cta: {
                link: "https://www.swiggy.com/restaurants/kfc-lake-vastrapur-ahmedabad-37941",
                text: "RESTAURANT_MENU",
                type: "WEBLINK",
              },
              widgetId:
                "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
            },
            {
              info: {
                id: "404427",
                name: "La Pino'z Pizza",
                cloudinaryImageId: "h9lpqchuffz5vvfzuup7",
                locality: "Near Sundarnagar",
                areaName: "VISHWESH TOWER NARANPURA",
                costForTwo: "₹400 for two",
                cuisines: [
                  "Pizzas",
                  "Pastas",
                  "Italian",
                  "Desserts",
                  "Beverages",
                ],
                avgRating: 4.4,
                veg: true,
                parentId: "4961",
                avgRatingString: "4.4",
                totalRatingsString: "1K+",
                sla: {
                  deliveryTime: 17,
                  lastMileTravel: 1.2,
                  serviceability: "SERVICEABLE",
                  slaString: "17 mins",
                  lastMileTravelString: "1.2 km",
                  iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                  nextCloseTime: "2023-12-25 03:00:00",
                  opened: true,
                },
                badges: {
                  imageBadges: [
                    {
                      imageId: "v1695133679/badges/Pure_Veg111.png",
                      description: "pureveg",
                    },
                  ],
                },
                isOpen: true,
                type: "F",
                badgesV2: {
                  entityBadges: {
                    imageBased: {
                      badgeObject: [
                        {
                          attributes: {
                            description: "pureveg",
                            imageId: "v1695133679/badges/Pure_Veg111.png",
                          },
                        },
                      ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                  },
                },
                aggregatedDiscountInfoV3: {
                  header: "₹125 OFF",
                  subHeader: "ABOVE ₹699",
                  discountTag: "FLAT DEAL",
                },
                orderabilityCommunication: {
                  title: {},
                  subTitle: {},
                  message: {},
                  customIcon: {},
                },
                differentiatedUi: {
                  displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                  differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                  },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
              },
              analytics: {
                context: "seo-data-58ab30b8-92c0-4ba5-b059-c403c4364cda",
              },
              cta: {
                link: "https://www.swiggy.com/restaurants/la-pinoz-pizza-near-sundarnagar-vishwesh-tower-naranpura-ahmedabad-404427",
                text: "RESTAURANT_MENU",
                type: "WEBLINK",
              },
              widgetId:
                "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
            },
            {
              info: {
                id: "114323",
                name: "Iscon Thal",
                cloudinaryImageId: "bd68ec66db6e8459145694c17f5aecde",
                locality: "SG Road",
                areaName: "Satellite",
                costForTwo: "₹200 for two",
                cuisines: [
                  "Gujarati",
                  "Thalis",
                  "Indian",
                  "Sweets",
                  "Desserts",
                  "Jain",
                ],
                avgRating: 4.4,
                veg: true,
                parentId: "107384",
                avgRatingString: "4.4",
                totalRatingsString: "10K+",
                sla: {
                  deliveryTime: 31,
                  lastMileTravel: 6.3,
                  serviceability: "SERVICEABLE",
                  slaString: "31 mins",
                  lastMileTravelString: "6.3 km",
                  iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                  nextCloseTime: "2023-12-24 22:15:00",
                  opened: true,
                },
                badges: {
                  imageBadges: [
                    {
                      imageId: "v1695133679/badges/Pure_Veg111.png",
                      description: "pureveg",
                    },
                  ],
                },
                isOpen: true,
                type: "F",
                badgesV2: {
                  entityBadges: {
                    imageBased: {
                      badgeObject: [
                        {
                          attributes: {
                            description: "pureveg",
                            imageId: "v1695133679/badges/Pure_Veg111.png",
                          },
                        },
                      ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                  },
                },
                aggregatedDiscountInfoV3: {
                  header: "₹175 OFF",
                  subHeader: "ABOVE ₹449",
                  discountTag: "FLAT DEAL",
                },
                orderabilityCommunication: {
                  title: {},
                  subTitle: {},
                  message: {},
                  customIcon: {},
                },
                differentiatedUi: {
                  displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                  differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                  },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
              },
              analytics: {
                context: "seo-data-58ab30b8-92c0-4ba5-b059-c403c4364cda",
              },
              cta: {
                link: "https://www.swiggy.com/restaurants/iscon-thal-sg-road-satellite-ahmedabad-114323",
                text: "RESTAURANT_MENU",
                type: "WEBLINK",
              },
              widgetId:
                "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
            },
            {
              info: {
                id: "49562",
                name: "Season 9",
                cloudinaryImageId: "nmtw1jxfhkurmmyosfly",
                locality: "Shivalik Yash",
                areaName: "Naranpura",
                costForTwo: "₹300 for two",
                cuisines: ["Indian", "Chinese", "Continental"],
                avgRating: 4.2,
                veg: true,
                parentId: "179676",
                avgRatingString: "4.2",
                totalRatingsString: "10K+",
                sla: {
                  deliveryTime: 26,
                  lastMileTravel: 1.3,
                  serviceability: "SERVICEABLE",
                  slaString: "26 mins",
                  lastMileTravelString: "1.3 km",
                  iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                  nextCloseTime: "2023-12-24 23:00:00",
                  opened: true,
                },
                badges: {
                  imageBadges: [
                    {
                      imageId: "v1695133679/badges/Pure_Veg111.png",
                      description: "pureveg",
                    },
                  ],
                },
                isOpen: true,
                type: "F",
                badgesV2: {
                  entityBadges: {
                    imageBased: {
                      badgeObject: [
                        {
                          attributes: {
                            description: "pureveg",
                            imageId: "v1695133679/badges/Pure_Veg111.png",
                          },
                        },
                      ],
                    },
                    textBased: {},
                    textExtendedBadges: {},
                  },
                },
                aggregatedDiscountInfoV3: {
                  header: "₹175 OFF",
                  subHeader: "ABOVE ₹449",
                  discountTag: "FLAT DEAL",
                },
                orderabilityCommunication: {
                  title: {},
                  subTitle: {},
                  message: {},
                  customIcon: {},
                },
                differentiatedUi: {
                  displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                  differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                  },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
              },
              analytics: {
                context: "seo-data-58ab30b8-92c0-4ba5-b059-c403c4364cda",
              },
              cta: {
                link: "https://www.swiggy.com/restaurants/season-9-shivalik-yash-naranpura-ahmedabad-49562",
                text: "RESTAURANT_MENU",
                type: "WEBLINK",
              },
              widgetId:
                "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
            },
            {
              info: {
                id: "37686",
                name: "McDonald's",
                cloudinaryImageId: "bb7ae131544c7d37e10fc5faf76f09d6",
                locality: "Navrangpura",
                areaName: "Navrangpura",
                costForTwo: "₹400 for two",
                cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
                avgRating: 4.4,
                parentId: "630",
                avgRatingString: "4.4",
                totalRatingsString: "10K+",
                sla: {
                  deliveryTime: 17,
                  lastMileTravel: 1.5,
                  serviceability: "SERVICEABLE",
                  slaString: "17 mins",
                  lastMileTravelString: "1.5 km",
                  iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                  nextCloseTime: "2023-12-25 02:45:00",
                  opened: true,
                },
                badges: {},
                isOpen: true,
                aggregatedDiscountInfoV2: {},
                type: "F",
                badgesV2: {
                  entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                  },
                },
                orderabilityCommunication: {
                  title: {},
                  subTitle: {},
                  message: {},
                  customIcon: {},
                },
                differentiatedUi: {
                  displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                  differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                  },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
              },
              analytics: {
                context: "seo-data-58ab30b8-92c0-4ba5-b059-c403c4364cda",
              },
              cta: {
                link: "https://www.swiggy.com/restaurants/mcdonalds-navrangpura-ahmedabad-37686",
                text: "RESTAURANT_MENU",
                type: "WEBLINK",
              },
              widgetId:
                "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
            },
            {
              info: {
                id: "37556",
                name: "Burger King",
                cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
                locality: "Himalaya Mall, Gurukul",
                areaName: "Memnagar",
                costForTwo: "₹350 for two",
                cuisines: ["Burgers", "American"],
                avgRating: 4.2,
                parentId: "166",
                avgRatingString: "4.2",
                totalRatingsString: "10K+",
                sla: {
                  deliveryTime: 25,
                  lastMileTravel: 3,
                  serviceability: "SERVICEABLE",
                  slaString: "25 mins",
                  lastMileTravelString: "3.0 km",
                  iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                  nextCloseTime: "2023-12-25 05:00:00",
                  opened: true,
                },
                badges: {},
                isOpen: true,
                type: "F",
                badgesV2: {
                  entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                  },
                },
                aggregatedDiscountInfoV3: {
                  header: "60% OFF",
                  subHeader: "UPTO ₹120",
                },
                orderabilityCommunication: {
                  title: {},
                  subTitle: {},
                  message: {},
                  customIcon: {},
                },
                differentiatedUi: {
                  displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                  differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                  },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
              },
              analytics: {
                context: "seo-data-58ab30b8-92c0-4ba5-b059-c403c4364cda",
              },
              cta: {
                link: "https://www.swiggy.com/restaurants/burger-king-himalaya-mall-gurukul-memnagar-ahmedabad-37556",
                text: "RESTAURANT_MENU",
                type: "WEBLINK",
              },
              widgetId:
                "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
            },
            {
              info: {
                id: "773472",
                name: "Pizza Hut",
                cloudinaryImageId: "978358a0d0caba4f4555b8e2147b467d",
                locality: "Vastrapur Lake",
                areaName: "Nexus mall",
                costForTwo: "₹350 for two",
                cuisines: ["Pizzas"],
                avgRating: 4,
                parentId: "721",
                avgRatingString: "4.0",
                totalRatingsString: "20+",
                sla: {
                  deliveryTime: 35,
                  lastMileTravel: 3,
                  serviceability: "SERVICEABLE",
                  slaString: "35 mins",
                  lastMileTravelString: "3.0 km",
                  iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                  nextCloseTime: "2023-12-25 00:00:00",
                  opened: true,
                },
                badges: {},
                isOpen: true,
                type: "F",
                badgesV2: {
                  entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                  },
                },
                aggregatedDiscountInfoV3: {
                  header: "ITEMS",
                  subHeader: "AT ₹179",
                },
                orderabilityCommunication: {
                  title: {},
                  subTitle: {},
                  message: {},
                  customIcon: {},
                },
                differentiatedUi: {
                  displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                  differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                  },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                isNewlyOnboarded: true,
                restaurantOfferPresentationInfo: {},
              },
              analytics: {
                context: "seo-data-58ab30b8-92c0-4ba5-b059-c403c4364cda",
              },
              cta: {
                link: "https://www.swiggy.com/restaurants/pizza-hut-vastrapur-lake-nexus-mall-ahmedabad-773472",
                text: "RESTAURANT_MENU",
                type: "WEBLINK",
              },
              widgetId:
                "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
            },
            {
              info: {
                id: "640739",
                name: "Virasat-E-Curry",
                cloudinaryImageId: "96603898b3bee282c35811d3b2e8f22f",
                locality: "Sunrise centre",
                areaName: "Vastrapur",
                costForTwo: "₹250 for two",
                cuisines: [
                  "North Indian",
                  "Mughlai",
                  "Tandoor",
                  "Indian",
                  "Punjabi",
                  "Biryani",
                  "Snacks",
                  "Seafood",
                  "Barbecue",
                  "Grill",
                  "Lucknowi",
                  "Home Food",
                  "Beverages",
                  "Desserts",
                  "Thalis",
                ],
                avgRating: 4.4,
                veg: true,
                parentId: "386420",
                avgRatingString: "4.4",
                totalRatingsString: "1K+",
                sla: {
                  deliveryTime: 31,
                  lastMileTravel: 3,
                  serviceability: "SERVICEABLE",
                  slaString: "31 mins",
                  lastMileTravelString: "3.0 km",
                  iconType: "ICON_TYPE_EMPTY",
                },
                availability: {
                  nextCloseTime: "2023-12-25 02:00:00",
                  opened: true,
                },
                badges: {},
                isOpen: true,
                type: "F",
                badgesV2: {
                  entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                  },
                },
                aggregatedDiscountInfoV3: {
                  header: "₹125 OFF",
                  subHeader: "ABOVE ₹499",
                  discountTag: "FLAT DEAL",
                },
                orderabilityCommunication: {
                  title: {},
                  subTitle: {},
                  message: {},
                  customIcon: {},
                },
                differentiatedUi: {
                  displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
                  differentiatedUiMediaDetails: {
                    mediaType: "ADS_MEDIA_ENUM_IMAGE",
                    lottie: {},
                    video: {},
                  },
                },
                reviewsSummary: {},
                displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
                restaurantOfferPresentationInfo: {},
              },
              analytics: {
                context: "seo-data-58ab30b8-92c0-4ba5-b059-c403c4364cda",
              },
              cta: {
                link: "https://www.swiggy.com/restaurants/virasat-e-curry-sunrise-centre-vastrapur-ahmedabad-640739",
                text: "RESTAURANT_MENU",
                type: "WEBLINK",
              },
              widgetId:
                "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
            },
          ],
          theme: "SeoRestaurantListingGridWidget",
        },
      },
    },
  },
};
export default cards;
